project:
  type: website
  output-dir: docs

website:
  title: "HEMT Monte Carlo Simulation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simulator.qmd
        text: Simulator
      - href: code.qmd
        text: Code
      - href: results.qmd
        text: Results

format:
  html:
    theme: cosmo
    css: styles.css
    toc: True
    code-fold: true

lang: ko